name: Actually Actors
favicon: null
layout_spectrum: 0.99706
typography_spectrum: 0.2456
title: 'What Actually Actors did next!'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#b2959a'
    - '#7e2658'
    - '#180f10'
    - '#527944'
  brandStrength: 0.5
  lightness: 0.828816848108545
  saturation: 0.47505525778979063
  rhythmicContrast: 0.4134092202875763
purpose: []
