name: Actually Actors
favicon: null
layout_spectrum: 0.5584573650266975
typography_spectrum: 0.59612
title: 'What Actually Actors did next!'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  brandStrength: 0.003992236452177167
  lightness: 0.828816848108545
  saturation: 0.47505525778979063
  rhythmicContrast: 0.4134092202875763
purpose: []
